networks:
  default:
    name: song_analysis_data_pipeline-network
    external: true
services:
  eventsim:
    build:
      context: ../..
      dockerfile: Docker/streaming/eventsim.Dockerfile
    container_name: eventsim
    # command: cd .. && cd app/eventsim-master && sh entrypoint.sh
    volumes:
      - ./data/streaming_data:/app/eventsim-master/streaming_data